# Generated by Django 5.1.1 on 2024-09-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
